name: epiml
channels:
- defaults
- glemaitre
dependencies:
- ipykernel=4.5.2=py35_0
- ipython=5.1.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.1=py35_0
- matplotlib=1.5.3=np111py35_1
- notebook=4.3.0=py35_0
- numpy=1.11.2=py35_0
- pandas=0.19.2=np111py35_0
- pytest=3.0.5=py35_0
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- scikit-image=0.12.3=np111py35_1
- scikit-learn=0.18.1=np111py35_0
- scipy=0.18.1=np111py35_0
- seaborn=0.7.1=py35_0
- six=1.10.0=py35_0
- imbalanced-learn=0.2.1=py35_0
- pip:
  - lime==0.1.1.19
  - xgboost==0.6a2

